### PR TITLE
Remove `ignore_timestamps_errors` flag

### PR DESCRIPTION
**Pull request by weiglszonja**
Using `ignore_timestamps_errors` currently does not guarantee that data has no gaps in it. 
https://github.com/NeuralEnsemble/python-neo/issues/1336
I think it is better to remove completely and if we see this error we can turn it on for investigating.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Wasn't this needed for a separate session https://github.com/catalystneuro/tye-lab-to-nwb/issues/29?

**Comment by weiglszonja** [comment]
Yes, but now since it's turned on by default in convert_session.py, we won't know whether other sessions have this issue but they were silently ignored.

**Comment by CodyCBakerPhD** [comment]
Ah, so perhaps it should be a session-level parameter and should be turned off by default then enabled on that one session that needed itt?

I know the conversion is done now, but just for precedence and future design of this kind of thing

**Comment by weiglszonja** [comment]
Yeah exactly for future proofing

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by samuelgarcia** [comment]
The main problem with the option `ignore_timestamps_errors=True` in `OpenEphysRawIO` is that they are no garanty that gaps are the same across channels. Wich is a bit dangerous because the get_analogsignal_chunk rely on the fact that channels have no gaps and are aligned.

If there is a high user demand no reading this formats when they are gaps I would need to improve the IO.

**Pull request merged**
